create database SistemaChamadaEbd;
use SistemaChamadaEbd;
show tables; 


CREATE TABLE TB_NIVELACESSO(
  ID_NIVELACESSO	  INT PRIMARY KEY AUTO_INCREMENT,
  NM_NIVELACESSO	VARCHAR(100),
  OBSERVACOES		VARCHAR(500)

);

CREATE TABLE TB_PROFESSOR(
  ID_PROFESSOR 		INT PRIMARY KEY AUTO_INCREMENT,
  NM_PROFESSOR		VARCHAR(100),
  CPF_PROF			VARCHAR(100) UNIQUE,
  OBSERVACOES		VARCHAR(500)

);

CREATE TABLE TB_LOGIN(
  ID_LOGIN			INT AUTO_INCREMENT PRIMARY KEY,
  ID_NIVELACESSO	INT,
  ID_PROFESSOR		INT,
  
  USUARIO		VARCHAR(100),
  SENHA			VARCHAR(200),

  FOREIGN KEY (ID_NIVELACESSO) REFERENCES TB_NIVELACESSO(ID_NIVELACESSO),
  FOREIGN KEY (ID_PROFESSOR) REFERENCES TB_PROFESSOR(ID_PROFESSOR) 
);