
create database SistemaChamadaEbd;
use SistemaChamadaEbd;
show tables; 


CREATE TABLE TB_NIVELACESSO(
  ID_NIVELACESSO	  	INT PRIMARY KEY AUTO_INCREMENT,
  NM_NIVELACESSO		VARCHAR(100),
  DS_OBSERVACOES		VARCHAR(500)

);

CREATE TABLE TB_PROFESSOR(
  ID_PROFESSOR 			INT PRIMARY KEY AUTO_INCREMENT,
  NM_PROFESSOR			VARCHAR(100),
  CPF_PROF				VARCHAR(100) UNIQUE,
  DS_OBSERVACOES		VARCHAR(500)

);

CREATE TABLE TB_LOGIN(
  ID_LOGIN			INT AUTO_INCREMENT PRIMARY KEY,
  ID_NIVELACESSO	INT,
  ID_PROFESSOR		INT,
  
  USUARIO		VARCHAR(100),
  SENHA			VARCHAR(200),

  FOREIGN KEY (ID_NIVELACESSO) REFERENCES TB_NIVELACESSO(ID_NIVELACESSO),
  FOREIGN KEY (ID_PROFESSOR) REFERENCES TB_PROFESSOR(ID_PROFESSOR) 
);

CREATE TABLE TB_ALUNO(

  ID_ALUNO			INT PRIMARY KEY AUTO_INCREMENT,
  ID_CLASSE			INT,
  
  NM_ALUNO	 		VARCHAR(100),
  DT_NASCIMENTO		DATE,
  CPF_ALUNO			VARCHAR(100) UNIQUE,
  NM_IDADE			INT,
  SITUACAOALUNO VARCHAR(100),
  
  FOREIGN KEY (ID_CLASSE) REFERENCES TB_CLASSE(ID_CLASSE)
);

CREATE TABLE TB_CLASSE(
  ID_CLASSE				INT PRIMARY KEY AUTO_INCREMENT,
  
  NM_CLASSE  			VARCHAR(100),
  FAIXAETARIA			VARCHAR(100),
  QTDALUNO				INT
);

CREATE TABLE TB_CLASSE_PROFESSOR(
  ID_CLASSEPROFESSOR	INT AUTO_INCREMENT PRIMARY KEY,
  ID_CLASSE				INT,
  ID_PROFESSOR			INT,
  
  FOREIGN KEY (ID_CLASSE) REFERENCES TB_CLASSE(ID_CLASSE),
  FOREIGN KEY (ID_PROFESSOR) REFERENCES TB_PROFESSOR(ID_PROFESSOR)

);

CREATE TABLE TB_AULA(
  ID_AULA 			   INT PRIMARY KEY AUTO_INCREMENT,
  ID_CLASSE			   INT,
  
  DT_AULA			   DATETIME,
  NR_QTDVISITANTETOTAL INT,
  NR_OFERTASTOTAL	   DECIMAL,

  FOREIGN KEY (ID_CLASSE) REFERENCES TB_CLASSE(ID_CLASSE)
);

CREATE TABLE TB_CHAMADA(

  ID_CHAMADA	 		INT PRIMARY KEY AUTO_INCREMENT,
  ID_AULA		 		INT,
  ID_ALUNO		 		INT,
  
  BT_PRESENCA		 	BOOLEAN,
  BT_PONTUALIDADE	 	BOOLEAN,
  BT_PARTICIPACAO		BOOLEAN,
  
  BT_BIBLIA		 	    BOOLEAN,
  BT_REVISTA 		 	BOOLEAN,
  NR_QTDVISITANTE		INT,
  VL_OFERTA				DECIMAL,
  DS_FORMAPAG			VARCHAR(100),
  
  FOREIGN KEY (ID_AULA) REFERENCES TB_AULA(ID_AULA),
  FOREIGN KEY (ID_ALUNO) REFERENCES TB_ALUNO(ID_ALUNO)
);



CREATE TABLE TB_CPF_LOGIN(
ID_CPF_LOGIN			  INT PRIMARY KEY AUTO_INCREMENT,
ID_LOGIN                  INT,

QTD_CPF                   INT,

FOREIGN KEY (ID_LOGIN) REFERENCES TB_LOGIN(ID_LOGIN)

);